### ISSUE TITLE
resize on orientation change

### ISSUE THREAD

**Issue by divanac** [nicklockwood/iCarousel#238]
Should I apply the transform to the carousel or carousel.contentView?

I have a carousel with 3 full items and partial view of the ones on either end.

If I apply the transform to the carousel, the problem is that the carousel scales but isnt interactive at either ends. The centre item is interactive and the adjacent items are also interactive, but only on the ends closest to the centre.

If I apply the transform to the carousel.contentView, all items are interactive, but I find that the selected item is no longer centred. I tried adjusting the carousel.contentOffset but could find the correct value.

Code is below
`
[UIView beginAnimations:nil context:NULL];
[UIView setAnimationDuration:duration];
[UIView setAnimationCurve:UIViewAnimationCurveEaseInOut];
if (UIInterfaceOrientationIsPortrait([[UIApplication sharedApplication] statusBarOrientation])) {
    carousel.transform = CGAffineTransformMakeScale(1.0 , 1.0);
} else {
    carousel.transform = CGAffineTransformMakeScale(0.7, 0.7);
}
[UIView commitAnimations];
[carousel reloadData];
`

Any help is appreciated.

**Comment by gerchicov-bp** [comment]
In general how to solve this issue? In portrait and landscape there are different empty places in the top and in the bottom of carousel.
The setting of frame does nothing.
The bigger frame does nothing too because I have problems with carousel top/bottom offsets and height. If I'll set a bigger frame then it will be partially outside the screen and again user couldn't scroll and access to all the items
