### ISSUE TITLE
EXC_BAD_ACCESS code 1 in setProcessedImageOnMainThread (FXImageView.m)

### ISSUE THREAD

**Issue by mkbg8** [nicklockwood/iCarousel#527]
Whenever I run on device (iPad Air in this case) I get the exception. The exact accused line is as follows:

```
        if (_crossfadeDuration)
        {
            //jump through a few hoops to avoid QuartzCore framework dependency
            CAAnimation *animation = [NSClassFromString(@"CATransition") animation];
            [animation setValue:@"kCATransitionFade" forKey:@"type"];
            animation.duration = _crossfadeDuration;
            [self.layer addAnimation:animation forKey:nil];
        } <<<< HERE
```

No exception is being thrown when running on simulators.

**Comment by eroltokalac** [comment]
Hi Nick, are you going to support arm64 also. I used your lib, and it's really very well solution, however due to Apple's restrictions app must be arm64 supported and I got a reject yesterday with an explanation of it has crashed on start, with the logs I've seen it's due to iCarousel, I'll help you on this however I don't know where to start. Regards,

**Comment by nicklockwood** [comment]
It does support arm64 and has done for some time, you just need to download the latest version.
