### ISSUE TITLE
version Swift 3.0 

### ISSUE THREAD

**Issue by sterzo** [nicklockwood/iCarousel#758]
Hello nicklockwood, your library is fantastic. There will be a servione in swift 3.0 or your project ends with objective-c ?

**Comment by Dschee** [comment]
Objective C is still officially supported and can be used in any Swift project. So I don't think a rewrite in Swift is needed. If ever a rewrite was needed, then probably because the underlying technologies (specifically the iOS frameworks) are changed.

So in my eyes, this is a no-issue and can be closed.

**Comment by nicklockwood** [comment]
@sterzo what @Dschee said, basically. iCarousel is closely tied to UIKit, which is still all Objective-C, so I don't see much to be gained from a  rewrite. In a few years maybe.
